version: '3.9'

services:
  msgchannelmongo:
    image: mongo:latest
    container_name: msgchannelmongo
    ports:
      - "5440:5440"
    environment:
      - MONGO_INITDB_ROOT_USERNAME='root'
      - MONGO_INITDB_ROOT_PASSWORD='example'
    volumes:
      - db-data:/data/db

  msgchannel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: msgchannel
    ports:
      - "8082:8082"
      - "5004:5004"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    command: java -jar -Dmicronaut.environments=local application.jar


networks:
  default:
    name: msg-service

volumes:
  db-data:
    external: false